#!/bin/bash
#
# setup_app.sh
#
# Script that installs and configure the r_studio demo application on the fgsg
#
source commons.sh

DEBUG=1
DOCKER_USER=duser
DOCKER_USER_PASS= # This will be generated by the script itself
DOCKER_USER_HOST=fgsg.ct.infn.it
DOCKER_PKEY= # This will be generated by the script itself
SETUP_ACTIONS_DIR=setup_actions # Folder containing actions
SETUP_APP_LOG=setup_app.log
FGAPI_TOKEN="XXX" # Token to be used for fgAPIServer APIs
APP_NAME=r-studio
APP_INFRA_NAME=$DOCKER_USER@fgsg.ct.infn.it
APP_INFRA_DESC="$DOCKER_USER@$DOCKER_USER_HOST, used to run docker containers"
APP_FILE_DIR=./app_files

report_failure() {
  out "failed" 0 1
  out ""
  out "---------------------------------------" 
  out " Reporting: '$ACTION_NAME'"
  out "---------------------------------------"
  out "Installation step: $action"
  out "Description: $DESC"
  out "Last action log: "
  outf $ACTION_OUT
  exit 1
}

report_done() {
  out "done" 0 1
  debugging &&\
    out "" &&\
    out "---------------------------------------" &&\
    out " Action log: '$ACTION_NAME'"
    out "---------------------------------------" &&\
    out "" &&\
    outf $ACTION_OUT &&\
    out ""
}

# Setup actions
# Vecror holding setup actions
DOCKER_USER_PASS=$(date +%s | sha256sum | base64 | head -c 32)
echo "" > $SETUP_APP_LOG
LOG_OUTFILE=$SETUP_APP_LOG
chown $SUDO_USER:$SUDO_USER $LOG_OUTFILE
out "Starting to setup application: $APP_NAME" 
mktmp &&\
ACTION_OUT=$RES &&\
SETUP_ACTIONS=$(ls -1 $SETUP_ACTIONS_DIR | xargs echo) &&\
for action in $SETUP_ACTIONS; do
  ACTION_NAME=$(echo $action | sed 's/^....//')
  echo "" > $ACTION_OUT &&\
  out "Executing: $ACTION_NAME ... " 1 &&\
  source $SETUP_ACTIONS_DIR/$action 2>&1 >$ACTION_OUT &&\
  report_done ||\
  report_failure
done &&\
out "Installation successully accomplished"
